apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout }}    
spec:
  to:
    kind: Service
    name: {{ .Values.name }}
  port:
    targetPort: 3000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
