# -- String to partially override fullname template (will maintain the release name)
nameOverride: ""
# -- String to fully override fullname template
fullnameOverride: "vllm"

minReplicas: 1

tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Equal
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Equal
    value: "True"

servingModel:
  resources:
    limits:
      cpu: '4'
      memory: 20Gi
      nvidia.com/gpu: '1'
    requests:
      cpu: '2'
      memory: 16Gi
      nvidia.com/gpu: '1'

runtime:
  storageUri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.1-8b-instruct'
  timeout: 45m
  logLevel: DEBUG
  # 2.16 RHOAI with vLLM v0.6.3
  image: 'quay.io/modh/vllm@sha256:c86ff1e89c86bc9821b75d7f2bbc170b3c13e3ccf538bf543b1110f23e056316'

inferenceService:
  args:
    - "--max-model-len=23000"
    - "--gpu-memory-utilization=0.99"
