apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  config.json: | # Update me
    {
      BACKEND_URL: {{ tpl .Values.backend.url $ }}
    }
