apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  config.json: |
    {
      "BACKEND_URL": {{ tpl .Values.backend.url $ | quote }}
    }
  # Incase user sets `NODE_ENV` to development or test
  config-local.json: |
    {
      "BACKEND_URL": {{  tpl .Values.backend.url $ | quote }}
    }
