{{- if .Values.openid.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "labels" . | indent 4 }}
  name: {{ .Values.name }}-oauth
  namespace: {{ .Release.namespace }}
data:
  oauth2_proxy.cfg: |
{{- range $key, $val := .Values.openid.config }}
    {{ $key }} = {{ $val | quote }}
{{- end }}
{{- end }}
