kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "labels" . | nindent 4 }}
  # annotations:
  #   service.alpha.openshift.io/serving-cert-secret-name: "{{ .Values.name }}-certs"
spec:
  ports:
    - name: 3000-tcp
      protocol: TCP
      {{- if .Values.openid.enabled }}
      port: 4180
      targetPort: 4180
      {{ else }}
      port: 3000
      targetPort: 3000
      {{- end }}
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    deployment: {{ .Values.name }}
status:
  loadBalancer: {}
