labels:
  app: elasticsearch
  app.kubernetes.io/component: elasticsearch
  app.kubernetes.io/instance: elasticsearch
  app.kubernetes.io/name: elasticsearch
  app.kubernetes.io/part-of: chatbot-application

name: elasticsearch
#namespace: elasticsearch-operator  
tls: false

resources:
  requests:
    memory: 4Gi
    cpu: 1
  limits:
    memory: 4Gi
    cpu: 2

count: 3
version: 8.16.0