kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "lab-elastic-secret-job.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lab-elastic-secret-job.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
