apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {{ .Values.servingModel.name }}
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - env:
        - name: OLLAMA_MODELS
          value: /.ollama/models
        - name: OLLAMA_HOST
          value: 0.0.0.0
        - name: OLLAMA_KEEP_ALIVE
          value: '-1m'
        - name: OLLAMA_ORIGINS
          value: {{ .Values.allowedOrigins | quote }}
        - name: MODEL_PATH
          value: {{ .Values.servingModel.model.path }}
        - name: MODEL_FILE
          value: {{ .Values.servingModel.model.file | default "IGNORED"}}
      image: '{{ .Values.image }}'
      imagePullPolicy: {{ .Values.imagePullPolicy }}
      name: kserve-container
      ports:
        - containerPort: 11434
          name: http1
          protocol: TCP
      resources:
        {{- .Values.servingModel.resources | toYaml | nindent 8 }}
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: any
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
