---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: weaviate-db-volume-claim
  labels:
    {{- include "labels" . | nindent 4 }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.storageClass.size }}  
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
...
